import tkinter as tk
from tkinter import ttk
from core.plugin_system import BasePlugin


class GlowVisualizerTab:

    def __init__(self, parent, app):
        self.app = app
        self.frame = ttk.Frame(parent)
        self._build_ui()

    def _build_ui(self):

        title = ttk.Label(
            self.frame,
            text="Glow Visualizer",
            font=("Arial", 18)
        )
        title.pack(pady=15)

        control_frame = ttk.Frame(self.frame)
        control_frame.pack(pady=10)

        self.r = tk.IntVar(value=255)
        self.g = tk.IntVar(value=0)
        self.b = tk.IntVar(value=0)

        ttk.Label(control_frame, text="R").grid(row=0, column=0)
        ttk.Label(control_frame, text="G").grid(row=1, column=0)
        ttk.Label(control_frame, text="B").grid(row=2, column=0)

        r_scale = ttk.Scale(control_frame, from_=0, to=255, variable=self.r, command=self.update_preview)
        g_scale = ttk.Scale(control_frame, from_=0, to=255, variable=self.g, command=self.update_preview)
        b_scale = ttk.Scale(control_frame, from_=0, to=255, variable=self.b, command=self.update_preview)

        r_scale.grid(row=0, column=1, padx=10)
        g_scale.grid(row=1, column=1, padx=10)
        b_scale.grid(row=2, column=1, padx=10)

        self.canvas = tk.Canvas(self.frame, width=200, height=120)
        self.canvas.pack(pady=15)

        self.preview_box = self.canvas.create_rectangle(
            0, 0, 200, 120,
            fill="#ff0000"
        )

        self.cfg_preview = tk.Text(self.frame, height=8, width=80)
        self.cfg_preview.pack(pady=10)

        button_frame = ttk.Frame(self.frame)
        button_frame.pack(pady=10)

        ttk.Button(
            button_frame,
            text="Generate CFG",
            command=self.generate_cfg
        ).pack(side="left", padx=10)

        ttk.Button(
            button_frame,
            text="Add to Autoexec",
            command=self.add_to_autoexec
        ).pack(side="left", padx=10)

        self.update_preview()

    def update_preview(self, event=None):

        r = self.r.get()
        g = self.g.get()
        b = self.b.get()

        color = f'#{r:02x}{g:02x}{b:02x}'

        self.canvas.itemconfig(self.preview_box, fill=color)

    def generate_cfg(self):

        r = self.r.get()
        g = self.g.get()
        b = self.b.get()

        cfg = f"""// Glow generated by Glow Visualizer

cl_glow_survivor_r {r}
cl_glow_survivor_g {g}
cl_glow_survivor_b {b}

"""

        self.cfg_preview.delete("1.0", tk.END)
        self.cfg_preview.insert(tk.END, cfg)

    def add_to_autoexec(self):

        content = self.cfg_preview.get("1.0", tk.END)

        if hasattr(self.app, "autoexec_tab"):
            self.app.autoexec_tab.preview.insert(tk.END, "\n" + content)


class Plugin(BasePlugin):

    name = "Glow Visualizer"
    version = "1.0"
    author = "paradox32000"

    def on_load(self, app):

        tab = GlowVisualizerTab(app.tabControl, app)
        app.tabControl.add(tab.frame, text="Glow Visualizer")